# Generated by Django 5.1.1 on 2024-10-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='battery_capacity',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
