# Generated by Django 5.1.1 on 2024-10-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product_obj',
            new_name='product_object',
        ),
    ]
