# Generated by Django 5.1.1 on 2024-10-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_product_obj_review_product_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user_obj',
            new_name='user_object',
        ),
    ]
